# Generated by Django 6.0.5 on 2026-05-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracionsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'configuracionsistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historialreporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=11, null=True)),
                ('estado_nuevo', models.CharField(max_length=11)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField()),
            ],
            options={
                'db_table': 'historialreporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=500)),
                ('gravedad', models.CharField(max_length=8)),
                ('descripcion', models.TextField()),
                ('info_adicional', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen2', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen3', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estado', models.CharField(blank=True, max_length=11, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'reportes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposanomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anomalia', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'tiposanomalia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('correo_electronico', models.CharField(max_length=150, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=36, null=True)),
                ('verificado', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('direccion_residencia', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_cuenta', models.CharField(blank=True, max_length=9, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100, unique=True)),
                ('zona_geografica', models.CharField(max_length=13)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'zonas',
                'managed': False,
            },
        ),
    ]
