# Generated by Django 6.0.5 on 2026-06-24 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_zona', models.CharField(max_length=100, unique=True)),
                ('zona_geografica', models.CharField(max_length=13)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'zonas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracionsistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_actualizacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Configuración del sistema',
                'verbose_name_plural': 'Configuraciones del sistema',
                'db_table': 'configuracionsistema',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Tiposanomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_anomalia', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Tipo de anomalía',
                'verbose_name_plural': 'Tipos de anomalía',
                'db_table': 'tiposanomalia',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('correo_electronico', models.CharField(max_length=150, unique=True)),
                ('contrasena_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=36, null=True)),
                ('verificado', models.IntegerField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField()),
                ('ultimo_acceso', models.DateTimeField(blank=True, null=True)),
                ('direccion_residencia', models.CharField(blank=True, max_length=200, null=True)),
                ('numero_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_perfil', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_cuenta', models.CharField(blank=True, max_length=9, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='safezone_app.roles')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barrio', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=500)),
                ('gravedad', models.CharField(max_length=8)),
                ('descripcion', models.TextField()),
                ('info_adicional', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen2', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen3', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('estado', models.CharField(blank=True, max_length=11, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_reporte', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('id_tipo_anomalia', models.ForeignKey(db_column='id_tipo_anomalia', on_delete=django.db.models.deletion.DO_NOTHING, to='safezone_app.tiposanomalia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safezone_app.usuarios')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'db_table': 'reportes',
            },
        ),
        migrations.CreateModel(
            name='Historialreporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=11, null=True)),
                ('estado_nuevo', models.CharField(max_length=11)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField()),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='safezone_app.reportes')),
                ('usuario_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='safezone_app.usuarios')),
            ],
            options={
                'verbose_name': 'Historial de reporte',
                'verbose_name_plural': 'Historial de reportes',
                'db_table': 'historialreporte',
            },
        ),
    ]
