# Generated by Django 6.0.5 on 2026-06-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safezone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionsistema',
            options={'verbose_name': 'Configuración del sistema', 'verbose_name_plural': 'Configuraciones del sistema'},
        ),
        migrations.AlterModelOptions(
            name='historialreporte',
            options={'verbose_name': 'Historial de reporte', 'verbose_name_plural': 'Historial de reportes'},
        ),
        migrations.AlterModelOptions(
            name='reportes',
            options={'verbose_name': 'Reporte', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='tiposanomalia',
            options={'verbose_name': 'Tipo de anomalía', 'verbose_name_plural': 'Tipos de anomalía'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
