# Generated by Django 6.0.5 on 2026-08-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('safezone_app', '0002_reportes_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonas',
            options={},
        ),
    ]
